# Generated by Django 5.0.2 on 2024-02-18 08:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_doctor_patients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labo',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_tel', models.CharField(blank=True, max_length=20, null=True)),
                ('isLabo', models.BooleanField(default=True)),
                ('patients', models.ManyToManyField(blank=True, related_name='Labo', to='main.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
