# Generated by Django 5.0.2 on 2024-02-18 08:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_labo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maladie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('isChronic', models.BooleanField(default=False)),
                ('maladie_type', models.CharField(choices=[('CARDIOVASCULAIRE', 'Maladie cardiovasculaire'), ('RESPIRATOIRE', 'Maladie respiratoire'), ('INFECTIEUSE', 'Maladie infectieuse'), ('AUTOIMMUNE', 'Maladie auto-immune'), ('MENTALE', 'Maladie mentale'), ('GENETIQUE', 'Maladie génétique'), ('CANCER', 'Cancer'), ('METABOLIQUE', 'Trouble métabolique'), ('NEUROLOGIQUE', 'Trouble neurologique'), ('AUTRE', 'Autre')], max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='isPrivee',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MedicamentDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ratio', models.IntegerField(default=0)),
                ('duree', models.IntegerField(default=7)),
                ('isChronic', models.BooleanField(default=False)),
                ('medicament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.medicament')),
            ],
        ),
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('radio_type', models.CharField(choices=[('Radiographie', 'RADIOGRAPHIE'), ('Tomodensitométrie (TDM)', 'SCAN'), ('Imagerie par Résonance Magnétique (IRM)', 'IRM'), ('Tomographie par Émission de Positons (TEP)', 'TEP'), ('Échographie', 'ÉCHOGRAPHIE'), ('Mammographie', 'MAMMOGRAPHIE'), ('Fluoroscopie', 'FLUOROSCOPIE'), ('Imagerie en Médecine Nucléaire', 'MÉDECINE_NUCLÉAIRE'), ('Autre', 'AUTRE')], max_length=80)),
                ('radio_file', models.FileField(blank=True, null=True, upload_to='radio_files/')),
                ('Labo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radios', to='main.labo')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radios', to='main.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='main.doctor')),
                ('maladie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.maladie')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='main.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Ordonance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medicamentDetails', models.ManyToManyField(blank=True, null=True, to='main.medicamentdetails')),
                ('report', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.report')),
            ],
        ),
    ]
