# Generated by Django 5.0.2 on 2024-02-18 09:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_ordonance_medicamentdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('operation_type', models.CharField(choices=[('CHIRURGIE_CARDIAQUE', 'Chirurgie cardiaque'), ('CHIRURGIE_ORTHOPEDIQUE', 'Chirurgie orthopédique'), ('CHIRURGIE_ESTHETIQUE', 'Chirurgie esthétique'), ('CHIRURGIE_DIGESTIVE', 'Chirurgie digestive'), ('CHIRURGIE_VASCULAIRE', 'Chirurgie vasculaire'), ('CHIRURGIE_NEUROLOGIQUE', 'Chirurgie neurologique'), ('CHIRURGIE_UROLOGIQUE', 'Chirurgie urologique'), ('CHIRURGIE_GYNECOLOGIQUE', 'Chirurgie gynécologique'), ('CHIRURGIE_THORACIQUE', 'Chirurgie thoracique'), ('CHIRURGIE_OPHTALMOLOGIQUE', 'Chirurgie ophtalmologique'), ('AUTRE', 'Autre')], max_length=100)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='main.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='main.profile')),
            ],
        ),
    ]
