# Generated by Django 5.0.2 on 2024-02-18 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_labo_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radio',
            old_name='Labo',
            new_name='labo',
        ),
    ]
