# Generated by Django 5.0.2 on 2024-02-18 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_report_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordonance',
            old_name='medicamentDetails',
            new_name='medicamentsDetails',
        ),
        migrations.AlterField(
            model_name='ordonance',
            name='report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordonance', to='main.report'),
        ),
    ]
