# Generated by Django 5.0.2 on 2024-02-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_medicamentdetails_ordonance_medicamentsdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamentdetails',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicamentdetails',
            name='ratio',
            field=models.IntegerField(default=1),
        ),
    ]
