# Generated by Django 5.0.2 on 2024-02-18 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_medicamentdetails_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordonance',
            name='medicamentsDetails',
        ),
        migrations.AddField(
            model_name='medicamentdetails',
            name='ordonance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ordonance'),
        ),
        migrations.AlterField(
            model_name='medicamentdetails',
            name='medicament',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.medicament'),
        ),
    ]
