# Generated by Django 5.0.2 on 2024-02-18 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_ordonance_medicamentsdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamentdetails',
            name='medicament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.medicament'),
        ),
        migrations.AlterField(
            model_name='medicamentdetails',
            name='ordonance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='main.ordonance'),
        ),
    ]
