# Generated by Django 5.0.2 on 2024-02-18 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_medicamentdetails_medicament_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordonance',
            name='report',
        ),
        migrations.AddField(
            model_name='ordonance',
            name='ordonance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordonance', to='main.report'),
        ),
    ]
