# Generated by Django 5.0.2 on 2024-02-18 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_ordonance_report_ordonance_ordonance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordonance',
            old_name='ordonance',
            new_name='report',
        ),
    ]
